name: debians

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  default:
    strategy:
      fail-fast: false

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "hi"